### ISSUE TITLE
Scrolling confetti off-screen causes system freeze due to all memory being consumed

### ISSUE THREAD

**Issue by Majr25** [bgrins/xbl-analysis#17]
Congrats on getting rid of all the XBL! However, the celebration confetti is a little too enthusiastic as when it is scrolled far enough off-screen it starts rapidly eating all GPU memory, and then moves on to system memory until the system freezes. Scrolling the confetti back on screen causes all the memory to be released almost immediately once the system recovers. Tested on latest firefox release as well as latest nightly on a fresh profile with webrender enabled.

[3 separate videos](https://github.com/bgrins/xbl-analysis/files/3800119/Videos.zip) as the recording stops working properly after the memory is used.

**Comment by bgrins** [comment]
Thanks for the heads up! I'm going to remove it rather than track down the performance issue.

**Comment by bgrins** [comment]
Pushed up the change.
