### ISSUE TITLE
List CSS selectors of each binding in the tree view

### ISSUE THREAD

**Issue by timdream** [bgrins/xbl-analysis#5]
Custom elements are "bound" to element names and element names only, whereas XBL bindings can be bound to any matching selector.

In order to convert applicable bindings to custom elements, we'll need to identify the CSS selector usage of these bindings. Let's add a feature to the tree view here and figure out what's needed next.

**Comment by bgrins** [comment]
I think we could stick this directly in the tree script: https://github.com/bgrins/xbl-analysis/blob/gh-pages/scripts/build-xbl-tree.js only when rev is undefined. In that case it would only be printed on the latest version of tree and not archived versions, but it may be less work to maintain since if a css file got (re)moved we only have to worry about master and not the date the change happened.

**Comment by bgrins** [comment]
List of files gathered from https://searchfox.org/mozilla-central/search?q=-moz-binding%3A&path=.css and running `[...document.querySelectorAll(".results tr:not(.result-head)")].forEach(r=>r.style.display="none")` in the console:

```
browser/base/content/browser.css
browser/base/content/tabbrowser.css
browser/components/downloads/content/downloads.css
browser/components/places/content/places.css
browser/components/preferences/handlers.css
browser/components/search/content/searchbarBindings.css
browser/extensions/formautofill/content/formautofill.css
browser/themes/linux/browser.css
browser/themes/linux/places/organizer.css
browser/themes/shared/downloads/progressmeter.inc.css
layout/style/contenteditable.css
layout/style/res/forms.css
layout/style/res/html.css
layout/style/res/number-control.css
layout/svg/svg.css
mobile/android/themes/geckoview/content.css
toolkit/content/minimal-xul.css
toolkit/content/widgets/videocontrols.css
toolkit/content/xul.css
toolkit/mozapps/extensions/content/blocklist.css
toolkit/mozapps/extensions/content/extensions.css
toolkit/mozapps/extensions/content/xpinstallConfirm.css
toolkit/mozapps/handling/content/handler.css
toolkit/mozapps/update/content/updates.css
toolkit/pluginproblem/content/pluginProblemBinding.css
toolkit/pluginproblem/content/pluginReplaceBinding.css
toolkit/themes/linux/global/global.css
toolkit/themes/linux/mozapps/viewsource/viewsource.css
toolkit/themes/osx/global/global.css
toolkit/themes/osx/global/nativescrollbars.css
toolkit/themes/windows/global/global.css
toolkit/themes/windows/global/xulscrollbars.css
```

**Comment by bgrins** [comment]
We should be able to request the files from github using something similar to this: https://github.com/bgrins/xbl-analysis/blob/gh-pages/scripts/xbl-files.js
