### ISSUE TITLE
<marquee> is being removed in bug 1425874

### ISSUE THREAD

**Issue by ExE-Boss** [bgrins/xbl-analysis#9]
The [XBL Component Tree](https://bgrins.github.io/xbl-analysis/tree/#marquee) reports `<marquee>` as having no bug, despite the conversion to a normal HTML element being tracked in [bug 1425874](https://bugzil.la/1425874).

This has to be corrected in the [relevant Google Docs sheet](https://docs.google.com/spreadsheets/d/e/2PACX-1vSBOysww1PcGcB19Ew_NOUpPnQMGkP1RQGAOAoYMRvgVMWWhmcdjyOfLjvEDCC_F6nobE7Hu6ooaj7Q/pub#0R208), to which I don’t have write access.

**Comment by bgrins** [comment]
That bug won't actually remove the marquee bindings (although it will simplify them a lot since it'll move property handling to webidl).
